-- ============================================================
-- Lesson Mentor: Question Bank seed data
-- Generated from question-bank-data.js — DO NOT hand-edit;
-- regenerate this file if the source pools change.
-- ============================================================

INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-01', 'K-2', 'You want to learn about dinosaurs.', 'A-V', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-01', 'V', 'Look at a big picture book', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-01', 'A', 'Listen to a story read out loud', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-02', 'K-2', 'Your teacher is teaching new letters.', 'R-V', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-02', 'V', 'Look at letters on a poster', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-02', 'R', 'Trace and write them yourself', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-03', 'K-2', 'It''s centers time in the classroom.', 'K-V', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-03', 'V', 'Look at a picture chart on the wall', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-03', 'K', 'Build something with blocks', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-04', 'K-2', 'It''s story time on the rug.', 'A-R', 4);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-04', 'A', 'Listen to the teacher read out loud', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-04', 'R', 'Look at a book and point to the words', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-05', 'K-2', 'You''re learning a new song.', 'A-K', 5);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-05', 'A', 'Sing along and listen to the music', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-05', 'K', 'Do the hand motions and dance', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-06', 'K-2', 'We''re learning about plants.', 'K-R', 6);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-06', 'R', 'Look at a book with words about plants', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-06', 'K', 'Plant a real seed in the dirt', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-07', 'K-2', 'You are learning about the weather.', 'A-V', 7);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-07', 'V', 'Look at pictures of big storm clouds', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-07', 'A', 'Listen to a recording of real thunder', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-08', 'K-2', 'Your class is practicing adding numbers.', 'K-R', 8);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-08', 'R', 'Write the numbers on a whiteboard', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-08', 'K', 'Use plastic cubes to build groups', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-09', 'K-2', 'You want to find out how a puppy grows up.', 'K-V', 9);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-09', 'V', 'Watch a video of a puppy growing big', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-09', 'K', 'Visit a real dog and pet it', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-10', 'K-2', 'It''s time to learn your sight words.', 'A-R', 10);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-10', 'A', 'Sing a catchy rhyming alphabet song', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-10', 'R', 'Trace the words with a pencil', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-11', 'K-2', 'You are learning about bugs in nature.', 'A-K', 11);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-11', 'A', 'Hear the teacher explain where bugs live', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-11', 'K', 'Act out crawling like a caterpillar', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-12', 'K-2', 'You are learning how to draw shapes.', 'R-V', 12);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-12', 'V', 'Look at a colorful chart of shapes', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-12', 'R', 'Find shape names in a book', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-13', 'K-2', 'You are learning about different colors.', 'A-V', 13);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-13', 'V', 'Look at a bright rainbow poster', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-13', 'A', 'Listen to a poem about colors', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-14', 'K-2', 'You want to remember your teacher''s rules.', 'K-R', 14);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-14', 'R', 'Copy the rules checklist down', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-14', 'K', 'Roleplay the right way to line up', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-15', 'K-2', 'You are learning about fish in the ocean.', 'K-V', 15);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-15', 'V', 'Watch a video of fish swimming around', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-15', 'K', 'Touch real seashells and sand', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-16', 'K-2', 'You want to learn a new rhyme.', 'A-R', 16);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-16', 'A', 'Listen to your teacher say it twice', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-16', 'R', 'Look at the typed words on paper', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-17', 'K-2', 'Your class is learning about community helpers.', 'A-K', 17);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-17', 'A', 'Listen to a firefighter give a speech', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-17', 'K', 'Try on a heavy firefighter jacket', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-18', 'K-2', 'You are playing a matching game.', 'R-V', 18);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-18', 'V', 'Match colored pattern cards together', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-18', 'R', 'Match word labels to pictures', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-19', 'K-2', 'You are learning about the solar system.', 'R-V', 19);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-19', 'V', 'Look at a glowing model of the planets', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-19', 'R', 'Read a tiny flip-book about space', 2);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('k2-20', 'K-2', 'You need to practice your spelling words.', 'A-K', 20);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-20', 'A', 'Spell the words out loud to a friend', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('k2-20', 'K', 'Write words using finger-paint', 2);

INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-01', '3-5', 'Your class is learning about the water cycle. Rank these from most (1) to least (4) interesting to you.', NULL, 1001);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-01', 'V', 'Watch a video showing rain falling', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-01', 'A', 'Listen to a podcast explaining it', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-01', 'R', 'Read a short article about it', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-01', 'K', 'Build a model with a cup and plastic wrap', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-02', '3-5', 'You got a new board game. Rank how you''d most like to learn the rules.', NULL, 1002);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-02', 'V', 'Watch a how-to-play video', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-02', 'A', 'Have someone explain the rules out loud', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-02', 'R', 'Read the instruction booklet', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-02', 'K', 'Just start playing and figure it out', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-03', '3-5', 'Your teacher assigns a report on animals. Rank how you''d most like to find your information.', NULL, 1003);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-03', 'V', 'Look at a chart comparing animals', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-03', 'A', 'Listen to a nature documentary', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-03', 'R', 'Read a book about the animal', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-03', 'K', 'Visit a zoo or handle real animal items', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-04', '3-5', 'It''s time to study your spelling words. Rank these study methods.', NULL, 1004);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-04', 'V', 'Look at the words written in different colors', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-04', 'A', 'Say the words out loud and spell them aloud', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-04', 'R', 'Write the words several times', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-04', 'K', 'Spell the words by jumping on letter tiles on the floor', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-05', '3-5', 'Your class is starting a unit on space. Rank these activities.', NULL, 1005);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-05', 'V', 'Watch a video of a rocket launch', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-05', 'A', 'Listen to an astronaut''s story', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-05', 'R', 'Read a book about planets', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-05', 'K', 'Build a model rocket', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-06', '3-5', 'Math time! You''re learning multiplication. Rank these study methods.', NULL, 1006);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-06', 'V', 'Look at a multiplication chart', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-06', 'A', 'Listen to a multiplication song', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-06', 'R', 'Write out the times tables', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-06', 'K', 'Use counters or blocks to group numbers', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-07', '3-5', 'You''re picking how to present a class project. Rank these options.', NULL, 1007);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-07', 'V', 'Make a poster with pictures', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-07', 'A', 'Give an oral presentation', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-07', 'R', 'Write a report', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-07', 'K', 'Build a diorama or model', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-08', '3-5', 'Free reading time! Rank how you''d most like to enjoy a story.', NULL, 1008);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-08', 'V', 'Look at a picture book', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-08', 'A', 'Listen to an audiobook', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-08', 'R', 'Read a chapter book to yourself', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-08', 'K', 'Act out the story with friends', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-09', '3-5', 'Your class is studying maps and geography. Rank how you''d most like to learn about it.', NULL, 1009);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-09', 'V', 'Look at a large wall map', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-09', 'A', 'Listen to a traveler tell stories', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-09', 'R', 'Fill out a worksheet of capitals', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-09', 'K', 'Mold a map out of clay', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-10', '3-5', 'You''re learning the rules for a new recess game. Rank how you''d most like to learn them.', NULL, 1010);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-10', 'V', 'Look at a diagram of the court boundary lines', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-10', 'A', 'Listen to the coach explain it', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-10', 'R', 'Read the printed rule sheet', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-10', 'K', 'Jump into a practice round', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-11', '3-5', 'Your class is learning about symmetry in art. Rank how you''d most like to explore it.', NULL, 1011);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-11', 'V', 'Look at photos of symmetrical buildings', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-11', 'A', 'Talk through the definition with a peer', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-11', 'R', 'Copy the definition from the board', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-11', 'K', 'Fold paper and cut out shapes', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g35-12', '3-5', 'Your class is studying desert ecosystems. Rank how you''d most like to learn about it.', NULL, 1012);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-12', 'V', 'Look at an infographic food chain', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-12', 'A', 'Listen to desert night audio tracks', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-12', 'R', 'Read a short encyclopedia entry', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g35-12', 'K', 'Sort animal cards into habitat bins', 4);

INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-01', '6-12', 'You''re assigned a research project. Rank how you''d prefer to gather information.', NULL, 2001);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-01', 'V', 'Watch documentaries or video explainers', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-01', 'A', 'Listen to podcasts or interviews', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-01', 'R', 'Read articles, books, or journals', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-01', 'K', 'Conduct a hands-on experiment or field visit', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-02', '6-12', 'You''re studying for a big test. Rank your preferred study methods.', NULL, 2002);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-02', 'V', 'Make diagrams, charts, or color-coded notes', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-02', 'A', 'Talk it through with a study group, or record yourself explaining it', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-02', 'R', 'Rewrite notes and summarize in your own words', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-02', 'K', 'Use flashcards you physically sort and move', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-03', '6-12', 'Your teacher assigns a group project. Rank your preferred role on the team.', NULL, 2003);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-03', 'V', 'Designing the visual presentation or slides', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-03', 'A', 'Presenting and leading discussion', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-03', 'R', 'Writing the report', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-03', 'K', 'Building the prototype or model', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-04', '6-12', 'You''re learning a new skill outside of school. Rank how you''d prefer to start.', NULL, 2004);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-04', 'V', 'Watch a tutorial video', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-04', 'A', 'Discuss it with a mentor, or have someone explain it', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-04', 'R', 'Read a guide or manual', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-04', 'K', 'Just try it and learn by doing', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-05', '6-12', 'In science class, rank how you''d most like a new concept taught.', NULL, 2005);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-05', 'V', 'With diagrams and visual models', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-05', 'A', 'Through class discussion and lecture', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-05', 'R', 'Through the textbook reading', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-05', 'K', 'Through a lab experiment', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-06', '6-12', 'You''re choosing an elective or club. Rank what appeals to you most.', NULL, 2006);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-06', 'V', 'Photography, film, or art club', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-06', 'A', 'Debate, choir, or podcast club', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-06', 'R', 'Writing or journalism club', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-06', 'K', 'Robotics, sports, or shop club', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-07', '6-12', 'You need to remember historical events for class. Rank your preferred method.', NULL, 2007);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-07', 'V', 'Timeline with images', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-07', 'A', 'Listening to a historical podcast or lecture', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-07', 'R', 'Reading primary source documents', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-07', 'K', 'Reenacting events or visiting a historical site', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-08', '6-12', 'You''re preparing for a class presentation. Rank how you''d practice.', NULL, 2008);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-08', 'V', 'Watching examples of great presentations', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-08', 'A', 'Practicing out loud or rehearsing with someone', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-08', 'R', 'Writing out your script word for word', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-08', 'K', 'Practicing with props or moving through the space', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-09', '6-12', 'You''re learning to code a website. Rank how you''d prefer to start.', NULL, 2009);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-09', 'V', 'Watch a screen-recorded video walkthrough', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-09', 'A', 'Attend a live coding lecture with Q&A', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-09', 'R', 'Review a written HTML tag cheat-sheet', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-09', 'K', 'Type script directly into a compiler to see what breaks', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-10', '6-12', 'Your class is analyzing the plot of a novel. Rank how you''d most like to dig into it.', NULL, 2010);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-10', 'V', 'Fill out a plot-mountain visual diagram', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-10', 'A', 'Join a small-group Socratic seminar', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-10', 'R', 'Write a chapter-by-chapter outline', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-10', 'K', 'Act out a 1-minute scene with a classmate', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-11', '6-12', 'You''re learning geometry volume formulas. Rank your preferred study method.', NULL, 2011);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-11', 'V', 'Use color-coded flashcards with 3D shape diagrams', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-11', 'A', 'Explain the math logic out loud to a peer', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-11', 'R', 'Write out formulas multiple times', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-11', 'K', 'Measure physical boxes and objects in the room', 4);
INSERT INTO question_bank (id, grade_band, question_text, modality_pair, sort_order) VALUES ('g612-12', '6-12', 'Your class is analyzing a historic speech. Rank how you''d most like to study it.', NULL, 2012);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-12', 'V', 'Look at newsreel footage from that day', 1);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-12', 'A', 'Listen to the original audio recording', 2);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-12', 'R', 'Read the text transcript line-by-line', 3);
INSERT INTO question_options (question_id, modality_code, option_text, sort_order) VALUES ('g612-12', 'K', 'Read the speech aloud using the posture and pacing of the speaker', 4);
