insert into public.strategy_library
  (system, title, description, grade_bands, subjects, learning_styles, use_when, use_carefully)
values
  ('kagan', 'RallyCoach', 'Pairs take turns solving or explaining while the partner coaches with prompts and feedback.', '{g35,g68}', '{math,science}', '{A,K}', 'Students need guided practice with immediate peer feedback.', 'Students have not seen a model yet.'),
  ('kagan', 'Quiz-Quiz-Trade', 'Students circulate with prompt cards, answer, coach each other, then trade cards for repeated practice.', '{g35,g68,g912}', '{ela,science,social-studies}', '{A,K,R}', 'Vocabulary, review, and repeated retrieval practice.', 'Content is brand new and students cannot answer yet.'),
  ('siop', 'Comprehensible Input', 'Use modeling, visuals, gestures, and clear pacing so academic content is accessible.', '{k2,g35,g68}', '{math,science,social-studies}', '{V,A,K}', 'Students need modeling, visuals, or demonstration before practice.', 'Students are ready to try the task and need less teacher talk.'),
  ('siop', 'Content and Language Objectives', 'Post and revisit the content goal and the language students will use to show understanding.', '{k2,g35,g68,g912}', '{math,ela,science,social-studies}', '{V,R}', 'Lessons have new academic vocabulary or multilingual learner supports.', 'It is treated as a wall decoration instead of revisited.'),
  ('cer', 'Claim Evidence Reasoning Frame', 'Students answer with a claim, support it with data or observations, and connect the evidence with reasoning.', '{g35,g68,g912}', '{science,ela,social-studies}', '{R,V}', 'Students must explain a conclusion with evidence.', 'There is no evidence source for students to use.'),
  ('cer', 'Evidence Sort', 'Students sort observations into useful evidence, weak evidence, and unrelated details before writing.', '{g35,g68,g912}', '{science,social-studies,ela}', '{V,K,R}', 'Students need to choose which details truly support a claim.', 'The teacher already gave students the exact evidence to use.'),
  ('iep', 'Chunked Directions', 'Break tasks into short visible steps with one clear checkpoint before students move on.', '{k2,g35,g68,g912}', '{math,ela,science,social-studies}', '{V,R}', 'Multi-step tasks, stations, projects, and independent work.', 'Too many micro-steps slow fluent students down.'),
  ('iep', 'Sentence Frames', 'Provide partial language frames so students can focus on reasoning without losing response structure.', '{k2,g35,g68,g912}', '{ela,science,social-studies}', '{R,A}', 'Thinking is strong but language structure is a barrier.', 'Every student is forced to use the same frame even when ready to write independently.');
